Сдача ТЗ
Buhanzaz/java-filmorate pull request #20
Opened 2023-10-10 16:31 UTC by Buhanzaz

2023-10-11 16:42 UTC, mikita95 requested changes
Все сделано отлично. Оставил лишь пару замечаний

2023-10-11 16:42 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            findById(id);
Здесь, пожалуй, нет необхожимости в проверке на существование, так как удаление и так отработает и ничего страшного, если попытаться удалить несуществующую запись

2023-10-11 16:42 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +public class Genre implements Comparable<Genre> {
Не критично, но жанры в целом не очень сравнимы, лучше просто если нужно где-то упорядочить, там и прописать эту логику, иначе сейчас может смущать

2023-10-12 10:25 UTC, Nucleus1337 commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            findById(id);
Убрал проверку. Ошибка поднимается сразу.

2023-10-12 20:54 UTC, mikita95 approved these changes
Все отлично. Можно мержить пул-реквест

2023-10-13 15:21 UTC, merged