Controllers films users
Buhanzaz/java-filmorate pull request #4
Opened 2023-08-12 10:00 UTC by Buhanzaz

2023-08-12 17:06 UTC, mikita95 requested changes
Все сделано хорошо. Оставил несколько замечаний

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/FilmStorage.java
> +@Data
Data обычно используется над моделями данных - а здесь репозиторий. Также здесь не нужно геттеры и сеттеры id и всей мапы с данными

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/storage/UserStorage.java
> +@Data
Data обычно используется над моделями данных - а здесь репозиторий. Также здесь не нужно геттеры и сеттеры id и всей мапы с данными

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    final UserStorage storage;
Поле должно быть private

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    @PutMapping
Маппинг должен быть в контроллере, здесь эта аннотация не нужна

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    final FilmStorage storage;
Поле должно быть private

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void changeFilm(@Valid @RequestBody Film film){
RequestBody должен быть в контроллере

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    final UserService service;
Поле должно быть private

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Что-то с форматированием в этом файле

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public void setUserNameByLogin(User user, String text) {
Этот метод может быть private

2023-08-12 17:06 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    final FilmService service;
Поле может быть private

2023-08-12 22:16 UTC, Buhanzaz commented on .github/workflows/api-tests.yml
Я добавил файл обратно но выходит ошибка при проверке

2023-08-13 16:46 UTC, mikita95 requested changes
Все почти отлично :) Оставил еще несколько замечаний. Также сейчас не проходит сборка, нужно чтобы она проходила (checks), скорее всего нужно удалить файлы mvnw

2023-08-13 16:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +import java.io.IOException;
Что-то с форматированием здесь, должна быть пустая строка после импортов

2023-08-13 16:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    public void changeUser(@Valid @RequestBody User user) {
Здесь не должно быть @RequestBody - это относится к контроллеру

2023-08-13 16:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void changeFilm(Film film){
Не хватает пробела

2023-08-13 16:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public void addFilm(Film film){
Не хватает пробела

2023-08-13 16:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/exception/UserException.java
> +public class UserException extends RuntimeException{
Не хватает пробела

2023-08-13 16:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film postRequestFilm(@Valid @RequestBody Film film){
Не хватает пробела

2023-08-13 16:46 UTC, mikita95 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film putRequestFilm(@Valid @RequestBody Film film){
Не хватает пробела

2023-08-15 06:54 UTC, mikita95 requested changes
Все сделано хорошо. Только нужно вернут файлы проверки сборки и убедиться, что сборка проходит

2023-08-15 06:54 UTC, mikita95 commented on .github/workflows/api-tests.yml
Этот файл удалять или изменять не нужно :) Нужно его вернуть и сделать так, чтобы сборка проходила

2023-08-19 13:36 UTC, merged